### ISSUE TITLE
Bootstrap machine failed to download the release image on ARM

### ISSUE THREAD

**Issue by igorrudyk** [openshift/ocp-on-arm#17]
Hello guys,

Kindly ask you to review this error as this is blocking us to deploy Arm-based OpenShift on AWS.

**ERROR The bootstrap machine failed to download the release image**
INFO Pulling quay.io/openshift-release-dev/ocp-release-nightly@sha256:7a464d200ac371e3a6b66474fe99aec72a10db26f46929b315431b34c69fd95b...
INFO 5fc58e15ab811ba67bb68357f787585aca6af09c720f256d631be37a2480951c
**INFO ERROR: release image arch amd64 does not match host arch arm64**
FATAL Bootstrap failed to complete

**Comment by Prashanth684** [comment]
HI @igorrudyk ,

Are you building your own `openshift-install` binary from source? if so please use the OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE variable to override the release payload with an ARM release payload available here: https://mirror.openshift.com/pub/openshift-v4/aarch64/clients/ocp-dev-preview/.

Alternatively you could use the `openshift-install` binary here: https://console.redhat.com/openshift/install/aws/arm which encodes the correct ARM payload.

Thanks

**Comment by yselkowitz** [comment]
@igorrudyk, 

Based on the error message posted, it appears you may have been using an installer from an x86_64 (amd64) payload instead of one from an ARM payload.  Please ensure that `OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE` is *NOT* set in your environment, and that you use an installer downloaded from either https://console.redhat.com/openshift/install/aws/arm or https://mirror.openshift.com/pub/openshift-v4/aarch64/clients/ocp-dev-preview/pre-release/ regardless of which architecture on which you wish to run the installer.  (For instance, you can get an installer which runs on x86_64 Linux or Mac, but you still must get it from those ARM pages in order for it to install an ARM cluster.)

Please let us know if that works.  If not, please provide as much detail as possible about how you are trying to install, and please include the output of `openshift-install version`.

**Comment by igorrudyk** [comment]
Hello @yselkowitz , @Prashanth684 ,
Thank you for your help, it works.
